language: go

# Allow use in forks
go_import_path: github.com/vektra/mockery

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip

before_script:
  - go get ./mockery/...
  - go install -v ./cmd/...

script:
  - go generate github.com/vektra/mockery/165_case_0/test
  - ls -la ./165_case_0/test
  - cat ./165_case_0/test/mock_interface_test.go
  - mockery -name Iface -dir ./165_case_1/versioned -print
