language: go

# Allow use in forks
go_import_path: github.com/vektra/mockery

go:
  - 1.7.x
  - 1.8.x
  - tip

before_script:
  - go get ./...
  - go install -v ./cmd/...

script: go generate $GOPATH/src/github.com/vektra/mockery/165
