language: go

# Allow use in forks
go_import_path: github.com/vektra/mockery

go:
  - 1.7.x
  - 1.8.x
  - tip

before_script:
  - go get ./...
  - go install -v ./cmd/...

script:
  - go generate github.com/vektra/mockery/165
  - ls -la $GOPATH/src/github.com/vektra/mockery/165/mock_interface_test.go
  - cat $GOPATH/src/github.com/vektra/mockery/165/mock_interface_test.go
